# -*- coding: utf-8 -*-
"""NadaSoliman_Midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Ys3OvrucjRM1x1gouy4fOOc0nKQrVqG

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

# Machine learning is a field of science which is baesd on the abitlity of machines to create and develop algorithms,
#  and these algorithms enable machines to learn, recognize patterns, generate ideas, classify and predict through a statistical anlysis of a huge set of data
# by itself without a code designed to build the machine algorithm

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

# 1- Translating image to text by analyzing the content of the image and comparing it to previouse examples 
# 2- ready replys for emails by also analyzing what is written in the email and searching for a suitable reply in the data 
# 3- face recognition by analyzing features of human face comparing it to other millions of features

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

# example contains features and lables some informations and results and we give it to algorithms so it can learn from it so when we give it a new set of fetures it
# can predict the label according to what it learned from the first example 
# features are information by which label is defined 
# label is the result of the fetures for example when we have a pumpy feature the label is an orange
# feature vectore is a list of different features

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

# the use of Machine learning is a game changer specialy for designers, it is a new tool just like when computer first came and designer used it,
# Ml is a genrative system which can help designers by giving more ideas and more propapilities that designers did not think about it is also 
# a new canvas for them, in addition the spread of the use of artificial intellegnce and Ml between people will give the designer the ability to be 
# more connected with people, Ml also open the ways for communication designers to work with more designers from diffrent fields like science and architecture 
# designers 
#

"""Try to describe how you learn in algorithmic terms."""

# since i was a little kid i learned mostly from observing, memorizing and exparience, in this exact order. the first thing humans can do when they  
# are babies before they speak, read or write is see.
# we spend a lot of years from our childhood observing what other people around us do like they  press this button in the wall to open the light for example 
# so we understand that doing a certain action will give usa certain result and we save this informations in our mind and memorise them and then we try them so
# when we are in a dark room we will search for the button in the wall so we can open the light and i think this is the process of how we learn.

"""2Create a python dictionary for your name surname and year of birth."""

a = {'name':'nada', 'surname':'soliman', 'year':'2000'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if a['name'][0] == 'a':
  print('my initial is a')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(a['surname']) % 3 == 0:
  print('it is divisible')
else:
  print('not divisible')

"""Change your year of birth to 2678."""

a['year'] = '2678'

print(a)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

c = range(20,40)
for numbers in c:
  if numbers % 5 == 0:
    print(numbers)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

# n1_1 = 0.87      w1-2= 0.06        w1-1  = 0.12                       w1-4 = 0.76  
# n1_2 = 0.12      w2-2 = 0.12       w2-1  = 0.54                       w2-4 = 0.91
# n1_3 = 0.62      w3-2 = 0.47       w3-1  = 0.61                       w3-4 = 0.18

#N2_2 = n1_1 * w1-2  +  n1_2 * w2-2  +  n1_3 * w3-2
0.87 * 0.06 + 0.12 * 0.12 +  0.62 * 0.47



"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""